import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Inopan TDU App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header
          className={`
            h-16
            bg-transparent
            backdrop-blur-md
            flex
            fixed
            w-full
            px-6
          `}
        >
          <div>Inopan App</div>
        </header>

        <main className="pt-20 pb-8 min-h-screen">
          <Suspense fallback={"loading..."}>{children}</Suspense>
        </main>
      </body>
    </html>
  );
}
